services:

  frontend:
    build: ./frontend
    restart: on-failure

  backend:
    build: ./backend
    restart: on-failure
    env_file: ".env"
    depends_on:
      - db

  proxy:
    image: nginx:1.29-alpine
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    ports:
      - 80:80
      - 443:443

  db:
    image: postgres:18.0
    restart: on-failure
    env_file: ".env"
    volumes:
      - ./pgdata:/var/lib/postgresql/pgdata
